---
- name: Run role
  hosts: all
  become: true
  any_errors_fatal: true

  roles:
    - role: ansible-system_cleanpacker

  vars:
    cleanpacker_update_grub: false
    cleanpacker_clean_cloudinit: false
