---
- name: Import truncate_logs.yml
  ansible.builtin.import_tasks: truncate_logs.yml
  when: cleanpacker_truncate_logs | bool

- name: Import rebuild_hostkeys.yml
  ansible.builtin.import_tasks: rebuild_hostkeys.yml
  when: cleanpacker_rebuild_hostkeys | bool

- name: Import clean_cloudinit.yml
  ansible.builtin.import_tasks: clean_cloudinit.yml
  when: cleanpacker_clean_cloudinit | bool

- name: Import disable_services.yml
  ansible.builtin.import_tasks: disable_services.yml
  when: cleanpacker_disable_services | bool

- name: Import delete_unusedlocales.yml
  ansible.builtin.import_tasks: delete_unusedlocales.yml
  when: cleanpacker_delete_unusedlocales | bool

- name: Import disable_dns_netmanager.yml
  ansible.builtin.import_tasks: disable_dns_netmanager.yml
  when: cleanpacker_disable_dns_netmanager | bool

- name: Import clean_consul_node_id.yml
  ansible.builtin.import_tasks: clean_consul_node_id.yml
  when: cleanpacker_clean_consul_node_id | bool

# echo '> Cleaning the machine-id ...'
# truncate -s 0 /etc/machine-id
# rm /var/lib/dbus/machine-id
# ln -s /etc/machine-id /var/lib/dbus/machine-id

#- name: "Remove net-plan file"
#  ansible.builtin.file:
#    path: /etc/netplan/00-installer-config.yaml
#    state: absent
#
#- name: "Remove net-plan file"
#  ansible.builtin.file:
#    path: /etc/netplan/50-cloud-init.yaml
#    state: absent
