---
- name: "Find all host keys"
  ansible.builtin.find:
    paths: /etc/ssh/
    patterns: "ssh_host_*"
  register: ssh_host_keys

- name: "Remove hosts keys"
  ansible.builtin.file:
    path: "{{ item['path'] }}"
    state: absent
  no_log: true
  with_items: "{{ ssh_host_keys['files'] }}"
  notify:
    - reconfig ssh
    - restart sshd
