---
- name: "Check if logrotate exist"
  ansible.builtin.stat:
    path: /usr/sbin/logrotate
  register: rotate_bin

- name: "Rotate files"
  ansible.builtin.command: /usr/sbin/logrotate -f /etc/logrotate.conf
  when: rotate_bin.stat.exists
  failed_when: false
  changed_when: false

- name: "Find files to be removed"
  ansible.builtin.find:
    paths: /var/log
    file_type: file
    patterns: "*.1, *.gz"
  register: find_results

- name: "Remove files"
  ansible.builtin.file:
    path: "{{ item['path'] }}"
    state: absent
  no_log: true
  with_items: "{{ find_results['files'] }}"
