---
- name: "Check if logs were empty"
  ansible.builtin.stat:
    path: /var/log/audit/audit.log
  register: log1

- name: "Remove all files and dir in /var/logs"
  file:
    state: "{{ item }}"
    path: "/var/log/"
    owner: root
    group: root
    mode: '0755'
  with_items:
    - absent
    - directory
  when: log1.stat.exists

#- name: "Ensure /var/log/audit/audit.log exists"
#  ansible.builtin.stat:
#    path: /var/log/audit/audit.log
#  register: log1
#
#- name: "Truncate /var/log/audit/audit.log"
#  ansible.builtin.copy:
#    dest: "/var/log/audit/audit.log"
#    content: ""
#    mode: '0600'
#  when: log1.stat.exists
#
#- name: "Ensure /var/log/wtmp exists"
#  ansible.builtin.stat:
#    path: /var/log/wtmp
#  register: log2
#
#- name: "Truncate /var/log/wtmp"
#  ansible.builtin.copy:
#    dest: "/var/log/wtmp"
#    content: ""
#    mode: '0644'
#  when: log2.stat.exists
#
#- name: "Ensure /var/log/lastlog exists"
#  ansible.builtin.stat:
#    path: /var/log/lastlog
#  register: log3
#
#- name: "Truncate /var/log/lastlog"
#  ansible.builtin.copy:
#    dest: "/var/log/lastlog"
#    content: ""
#    mode: '0644'
#  when: log3.stat.exists
