---
- name: "Rebuild grub only apply to this distribution"
  when: (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '22') or ansible_distribution == 'OracleLinux'
  block:
    - name: "Ensure grub exist"
      ansible.builtin.stat:
        path: "{{ cleanpacker_grub_path }}"
      register: grub_exist

    - name: "Update grub configuration"
      ansible.builtin.lineinfile:
        path: "{{ cleanpacker_grub_path }}"
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="'
        line: "{{ cleanpacker_grub_cmd }}"
      when: grub_exist

    - name: "Rebuild grub"
      ansible.builtin.command: "{{ cleanpacker_rebuild_grub_cmd }}"
      changed_when: false
      when: grub_exist
