---
- name: Run role
  hosts: all
  become: true
  any_errors_fatal: true

  vars:
    cleanpacker_truncate_logs: true
    cleanpacker_rebuild_hostkeys: true
    cleanpacker_delete_unusedlocales: true
    cleanpacker_locales_keep: "en,fr"

  tasks:
    - name: Include role
      ansible.builtin.include_role:
        name: ansible-system_cleanpacker
